### ISSUE TITLE
DIRECTORY SEPARATOR compatibility with composer-overload-cache-dir-dev

### ISSUE THREAD

**Issue by armellarcier** [steevanb/composer-overload-class#1]
If my `composer.json` contains a `composer-overload-cache-dir-dev` path with UNIX directory separators like `var/cache/dev` and a Windows user tries to install, they'll have to replace `var/cache/dev` with `var\\cache\\dev` in `composer.json`.

That's because of a call to `explode($path, DIRECTORY_SEPARATOR)` I guess.

Thus this config cannot be cross-platform as is.

Any hints on how to get there ?

**Comment by armellarcier** [comment]
@steevanb Have you had time to read my comment ?

**Comment by steevanb** [comment]
Yes, i will fix it this week :)

**Comment by armellarcier** [comment]
I can help if you just point at the right file:line

**Comment by steevanb** [comment]
It should be fixed in `1.3.3`: https://github.com/steevanb/composer-overload-class/pull/2.

Tell me if it's ok, i can't test it on Windows.

**Comment by steevanb** [comment]
Do you have any feedback about the fix?
