### ISSUE TITLE
Critical: OverloadClass::getPhpForDuplicatedFile requires token update to keep up with Doctrine coding standards

### ISSUE THREAD

**Issue by Kalyse** [steevanb/composer-overload-class#4]
If you are overloading a class which uses the following:

https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php

You will see in the global class space, they use:

```
use Doctrine\ORM\Query;
use Exception;
use RuntimeException;
use function array_keys;
use function array_search;
use function count;
use function key;
use function reset;
use function sprintf;
```

The problem with that, is that 'function' is not a `T_STRING` token. It's a `T_FUNCTION`. 

There are two ways of solving this problem:

1)  Add... Something like this, within the `} elseif ($isGlobalUse && $token[0] === T_USE) {` check, which can be found here https://github.com/steevanb/composer-overload-class/blob/master/OverloadClass.php#L189

```
                   $walkForwardSteps = 1;
                    $continue = true;
                    do {
                        $nextNonWhitespaceToken = $tokens[$index + $walkForwardSteps];
                        if($nextNonWhitespaceToken[0] !== T_WHITESPACE){
                            $continue = false;
                        }
                        $walkForwardSteps++;
                    } while($continue);
                    if($nextNonWhitespaceToken[0] === T_STRING ) {
                        $uses[]      = static::getClassNameFromTokens($tokens, $index + 1);
                        $lastUseLine = $token[2];
                    }```

2) Update the getClassNameFromTokens() to understand that it's not just T_STRING and T_NS_SEPARATOR which needs to look forward. 


---------

Reason why this is needed... I asked on ##doctrine Slack and was told:

```
This is part of our coding style and an optimization. When you call a php function in your class with an namespace, PHP is looking for a function in that namespace first. If that function doesn't exist, it will be taken from the global namespace. The import of the functions will directly use the function from the given namespace. In this case directly the global one.```

**Comment by steevanb** [comment]
Thanks, i've fixed it here: #6.

You can update to `1.4.0` to get it.
